"""empty message

Revision ID: b492cfcb5d4f
Revises: 
Create Date: 2019-05-14 08:05:05.206504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b492cfcb5d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_union',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plane_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_number', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.String(length=128), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_number')
    )
    op.create_table('technician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('technician_number', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technician_number')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employees_number', sa.String(length=128), nullable=True),
    sa.Column('date_of_medical_check', sa.DATE(), nullable=True),
    sa.Column('is_technician', sa.Boolean(), nullable=True),
    sa.Column('union_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['union_id'], ['employee_union.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employees_number')
    )
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plane_model', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['plane_model'], ['plane_model.model_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kenya_port_authority_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('plane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=128), nullable=True),
    sa.Column('model_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_number'], ['plane_model.model_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('expertise_technician_table',
    sa.Column('expertise_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.id'], ),
    sa.PrimaryKeyConstraint('expertise_id', 'technician_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expertise_technician_table')
    op.drop_table('plane')
    op.drop_table('kenya_port_authority_test')
    op.drop_table('expertise')
    op.drop_table('employees')
    op.drop_table('technician')
    op.drop_table('plane_model')
    op.drop_table('employee_union')
    # ### end Alembic commands ###
